Address issue 47: name clashes in obfuscated types.
AqlaSolutions/AqlaSerializer pull request #48
Opened 2022-08-10 19:55 UTC by jdsheneman

The fix for the issue is contained in MetaType.Field.cs.  A unit test for the fix is in Issue47_Obfuscation.cs.

The changes to the .sln file are all the result of adding the Obfuscated project, a test target DLL.  This project builds a DLL from the Obfuscated.il, obfuscated to rename an inner class, two methods and a field to the same name "a".

2022-08-10 20:35 UTC, AqlaSolutions commented on src/protobuf-net/Meta/MetaType.Fields.cs
> +                else if (members.Length > 1)
This is an ambiguous case. You didn't add any logic to determine which one should be used. Picking just any of them is not an acceptable solution.

2022-08-10 20:36 UTC, AqlaSolutions commented on src/protobuf-net/Meta/MetaType.Fields.cs
> +                else if (members.Length > 1)
Will it work if we filter members before the Length check to take only fields and properties?

2022-08-10 20:37 UTC, AqlaSolutions requested changes
See comments

2022-08-10 20:38 UTC, AqlaSolutions commented
Also please target develop branch instead

2022-08-10 22:32 UTC, jdsheneman commented on src/protobuf-net/Meta/MetaType.Fields.cs
> +                else if (members.Length > 1)
I think it's possible to filter the elements first.

2022-08-10 22:33 UTC, jdsheneman commented on src/protobuf-net/Meta/MetaType.Fields.cs
> +                else if (members.Length > 1)
I'll work on the requested changes.

2022-08-11 13:57 UTC, closed without merging

2022-08-11 14:21 UTC, jdsheneman commented
I will reopen this pull request with new changes to a develop branch.