Address issue 47: name clashes in obfuscated types.
AqlaSolutions/AqlaSerializer pull request #49
Opened 2022-08-11 16:14 UTC by jdsheneman

I couldn't figure out how to limit the GetMember call to return only fields and properties, so I changed it to two explicit calls GetField and GetProperty.

2022-08-11 16:54 UTC, AqlaSolutions commented on src/protobuf-net/Meta/MetaType.Fields.cs
> +            mi = Type.GetField(memberName, Helpers.IsEnum(Type) ? BindingFlags.Static | BindingFlags.Public : BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
This should throw if you have both field and property but your code doesn't. You can't filer inside GetMember, instead do it afterwise with LINQ.

2022-08-11 16:55 UTC, AqlaSolutions requested changes
See comment

2022-08-11 16:59 UTC, jdsheneman commented on src/protobuf-net/Meta/MetaType.Fields.cs
> +            mi = Type.GetField(memberName, Helpers.IsEnum(Type) ? BindingFlags.Static | BindingFlags.Public : BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
OK.

2022-08-11 17:01 UTC, jdsheneman commented on src/protobuf-net/Meta/MetaType.Fields.cs
> +            mi = Type.GetField(memberName, Helpers.IsEnum(Type) ? BindingFlags.Static | BindingFlags.Public : BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
I'll see if it's possible to have a field and property with the same name in the IL.  If so, I'll add another test case for the exception.

2022-08-11 17:37 UTC, jdsheneman commented on src/protobuf-net/Meta/MetaType.Fields.cs
> +            mi = Type.GetField(memberName, Helpers.IsEnum(Type) ? BindingFlags.Static | BindingFlags.Public : BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
I was able to assemble IL with a property and field with the same name.  This works because the name of the backing field is different than the property name.  Such a class should be serializable.  Perhaps the logic for adding fields and properties should be separated to support this case.

2022-08-11 17:59 UTC, AqlaSolutions commented on src/protobuf-net/Meta/MetaType.Fields.cs
> +            mi = Type.GetField(memberName, Helpers.IsEnum(Type) ? BindingFlags.Static | BindingFlags.Public : BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
I know that they might have the same name. This scenario is currently unsupported and should throw exception.

2022-08-12 00:17 UTC, jdsheneman commented on src/protobuf-net/Meta/MetaType.Fields.cs
> +            mi = Type.GetField(memberName, Helpers.IsEnum(Type) ? BindingFlags.Static | BindingFlags.Public : BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
Updated code is in the third commit.  an exception is thrown when a field and property have the same name.

2022-08-12 06:14 UTC, AqlaSolutions commented on src/protobuf-net/Meta/MetaType.Fields.cs
> +                .Where(x => x.MemberType == MemberTypes.Field || x.MemberType == MemberTypes.Property).ToArray();
According to the later check for null, `Type.GetMember` might return null. If so, there should be a null coalescing operator `?` before `.Where`.

2022-08-12 06:15 UTC, AqlaSolutions requested changes
See comments

2022-08-12 12:52 UTC, jdsheneman commented on src/protobuf-net/Meta/MetaType.Fields.cs
> +                .Where(x => x.MemberType == MemberTypes.Field || x.MemberType == MemberTypes.Property).ToArray();
Done.

2022-08-12 13:29 UTC, AqlaSolutions commented on src/protobuf-net/Meta/MetaType.Fields.cs
> +            if (members.Length == 1) mi = members[0];
Why did you delete `members != null && ` from here? It should be there.

2022-08-12 13:29 UTC, AqlaSolutions requested changes
See comment

2022-08-12 13:36 UTC, jdsheneman commented on src/protobuf-net/Meta/MetaType.Fields.cs
> +            if (members.Length == 1) mi = members[0];
ReSharper pointed out that the result of ToArray will never be null so the check was not needed.

2022-08-14 21:19 UTC, AqlaSolutions approved these changes

2022-08-14 21:21 UTC, merged